---
deployment:
  tasks:
    - set -exv
    - export DEPLOYPATH=/home/utahkiar/public_html/
    - echo "--- Copying files ---"
    - /bin/cp -vR * $DEPLOYPATH
    - echo "--- Copying hidden files ---"
    - /bin/cp -vR .[^.]* $DEPLOYPATH || echo "No hidden files to copy"
    - echo "--- Done ---"